-- Creates schemas
CREATE SCHEMA INVENTORY;
CREATE SCHEMA ITEM;

-- CREATE TYPE rareness AS ENUM ('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY');
-- CREATE TYPE position AS ENUM ('TOP', 'BOTTOM', 'LEFT', 'RIGHT');

CREATE TABLE ITEM.CARD(
	CD_CARD     SERIAL PRIMARY KEY NOT NULL UNIQUE,
	NM_CARD     TEXT               NOT NULL,
	DSC_CARD    TEXT               NOT NULL,
	VL_ATTACK   DECIMAL(10, 2)     NOT NULL DEFAULT 10,
	VL_DEFFENSE DECIMAL(10, 2)     NOT NULL DEFAULT 10,
	HP_USES     DECIMAL(10, 2)     NOT NULL DEFAULT 10.2,
	VL_PRICE    DECIMAL(10, 2)     NOT NULL,
	VL_RARENESS TEXT               NOT NULL CHECK(VL_RARENESS IN ('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY'))
);

CREATE TABLE ITEM.FRAGMENT(
	CD_FRAGMENT  SERIAL PRIMARY KEY                NOT NULL UNIQUE,
	-- TM_GENERATED TIMESTAMP                         NOT NULL,
	VL_POSITION  TEXT                              NOT NULL ,
	ID_CARD      INT                               REFERENCES ITEM.CARD(CD_CARD),
	constraint position CHECK(VL_POSITION IN ('TOP', 'BOTTOM', 'LEFT', 'RIGHT') )
);

CREATE TABLE INVENTORY.DECK(
	CD_DECK  SERIAL PRIMARY KEY                NOT NULL UNIQUE,
	NM_USER  TEXT                              NOT NULL,
	QTD_CARD INT                               DEFAULT 1 NOT NULL,
	VL_HP    DECIMAL(10, 2)                    NOT NULL,
	ID_CARD  INT                               REFERENCES ITEM.CARD(CD_CARD)
);

CREATE TABLE INVENTORY.FRAGS(
	CD_FI SERIAL PRIMARY KEY NOT NULL UNIQUE,
	ID_FRAG INT REFERENCES ITEM.FRAGMENT(CD_FRAGMENT) NOT NULL,
	NM_USER TEXT NOT NULL
);


